// glip - Copyright 2019 Tomohisa Oda

use std::collections::HashMap;

lazy_static! {
    static ref FLAGS: HashMap<&'static str, &'static str> = {
        let mut m = HashMap::new();
        m.insert("🇦🇨", "Ascension Island");
        m.insert("🇦🇩", "Andorra");
        m.insert("🇦🇪", "United Arab Emirates");
        m.insert("🇦🇫", "Afghanistan");
        m.insert("🇦🇬", "Antigua & Barbuda");
        m.insert("🇦🇮", "Anguilla");
        m.insert("🇦🇱", "Albania");
        m.insert("🇦🇲", "Armenia");
        m.insert("🇦🇴", "Angola");
        m.insert("🇦🇶", "Antarctica");
        m.insert("🇦🇷", "Argentina");
        m.insert("🇦🇸", "American Samoa");
        m.insert("🇦🇹", "Austria");
        m.insert("🇦🇺", "Australia");
        m.insert("🇦🇼", "Aruba");
        m.insert("🇦🇽", "Åland Islands");
        m.insert("🇦🇿", "Azerbaijan");
        m.insert("🇧🇦", "Bosnia & Herzegovina");
        m.insert("🇧🇧", "Barbados");
        m.insert("🇧🇩", "Bangladesh");
        m.insert("🇧🇪", "Belgium");
        m.insert("🇧🇫", "Burkina Faso");
        m.insert("🇧🇬", "Bulgaria");
        m.insert("🇧🇭", "Bahrain");
        m.insert("🇧🇮", "Burundi");
        m.insert("🇧🇯", "Benin");
        m.insert("🇧🇱", "St. Barthélemy");
        m.insert("🇧🇲", "Bermuda");
        m.insert("🇧🇳", "Brunei");
        m.insert("🇧🇴", "Bolivia");
        m.insert("🇧🇶", "Caribbean Netherlands");
        m.insert("🇧🇷", "Brazil");
        m.insert("🇧🇸", "Bahamas");
        m.insert("🇧🇹", "Bhutan");
        m.insert("🇧🇻", "Bouvet Island");
        m.insert("🇧🇼", "Botswana");
        m.insert("🇧🇾", "Belarus");
        m.insert("🇧🇿", "Belize");
        m.insert("🇨🇦", "Canada");
        m.insert("🇨🇨", "Cocos (Keeling) Islands");
        m.insert("🇨🇩", "Congo - Kinshasa");
        m.insert("🇨🇫", "Central African Republic");
        m.insert("🇨🇬", "Congo - Brazzaville");
        m.insert("🇨🇭", "Switzerland");
        m.insert("🇨🇮", "Côte d’Ivoire");
        m.insert("🇨🇰", "Cook Islands");
        m.insert("🇨🇱", "Chile");
        m.insert("🇨🇲", "Cameroon");
        m.insert("🇨🇳", "China");
        m.insert("🇨🇴", "Colombia");
        m.insert("🇨🇵", "Clipperton Island");
        m.insert("🇨🇷", "Costa Rica");
        m.insert("🇨🇺", "Cuba");
        m.insert("🇨🇻", "Cape Verde");
        m.insert("🇨🇼", "Curaçao");
        m.insert("🇨🇽", "Christmas Island");
        m.insert("🇨🇾", "Cyprus");
        m.insert("🇨🇿", "Czechia");
        m.insert("🇩🇪", "Germany");
        m.insert("🇩🇬", "Diego Garcia");
        m.insert("🇩🇯", "Djibouti");
        m.insert("🇩🇰", "Denmark");
        m.insert("🇩🇲", "Dominica");
        m.insert("🇩🇴", "Dominican Republic");
        m.insert("🇩🇿", "Algeria");
        m.insert("🇪🇦", "Ceuta & Melilla");
        m.insert("🇪🇨", "Ecuador");
        m.insert("🇪🇪", "Estonia");
        m.insert("🇪🇬", "Egypt");
        m.insert("🇪🇭", "Western Sahara");
        m.insert("🇪🇷", "Eritrea");
        m.insert("🇪🇸", "Spain");
        m.insert("🇪🇹", "Ethiopia");
        m.insert("🇪🇺", "European Union");
        m.insert("🇫🇮", "Finland");
        m.insert("🇫🇯", "Fiji");
        m.insert("🇫🇰", "Falkland Islands");
        m.insert("🇫🇲", "Micronesia");
        m.insert("🇫🇴", "Faroe Islands");
        m.insert("🇫🇷", "France");
        m.insert("🇬🇦", "Gabon");
        m.insert("🇬🇧", "United Kingdom");
        m.insert("🇬🇩", "Grenada");
        m.insert("🇬🇪", "Georgia");
        m.insert("🇬🇫", "French Guiana");
        m.insert("🇬🇬", "Guernsey");
        m.insert("🇬🇭", "Ghana");
        m.insert("🇬🇮", "Gibraltar");
        m.insert("🇬🇱", "Greenland");
        m.insert("🇬🇲", "Gambia");
        m.insert("🇬🇳", "Guinea");
        m.insert("🇬🇵", "Guadeloupe");
        m.insert("🇬🇶", "Equatorial Guinea");
        m.insert("🇬🇷", "Greece");
        m.insert("🇬🇸", "South Georgia & South Sandwich Islands");
        m.insert("🇬🇹", "Guatemala");
        m.insert("🇬🇺", "Guam");
        m.insert("🇬🇼", "Guinea-Bissau");
        m.insert("🇬🇾", "Guyana");
        m.insert("🇭🇰", "Hong Kong SAR China");
        m.insert("🇭🇲", "Heard & McDonald Islands");
        m.insert("🇭🇳", "Honduras");
        m.insert("🇭🇷", "Croatia");
        m.insert("🇭🇹", "Haiti");
        m.insert("🇭🇺", "Hungary");
        m.insert("🇮🇨", "Canary Islands");
        m.insert("🇮🇩", "Indonesia");
        m.insert("🇮🇪", "Ireland");
        m.insert("🇮🇱", "Israel");
        m.insert("🇮🇲", "Isle of Man");
        m.insert("🇮🇳", "India");
        m.insert("🇮🇴", "British Indian Ocean Territory");
        m.insert("🇮🇶", "Iraq");
        m.insert("🇮🇷", "Iran");
        m.insert("🇮🇸", "Iceland");
        m.insert("🇮🇹", "Italy");
        m.insert("🇯🇪", "Jersey");
        m.insert("🇯🇲", "Jamaica");
        m.insert("🇯🇴", "Jordan");
        m.insert("🇯🇵", "Japan");
        m.insert("🇰🇪", "Kenya");
        m.insert("🇰🇬", "Kyrgyzstan");
        m.insert("🇰🇭", "Cambodia");
        m.insert("🇰🇮", "Kiribati");
        m.insert("🇰🇲", "Comoros");
        m.insert("🇰🇳", "St. Kitts & Nevis");
        m.insert("🇰🇵", "North Korea");
        m.insert("🇰🇷", "South Korea");
        m.insert("🇰🇼", "Kuwait");
        m.insert("🇰🇾", "Cayman Islands");
        m.insert("🇰🇿", "Kazakhstan");
        m.insert("🇱🇦", "Laos");
        m.insert("🇱🇧", "Lebanon");
        m.insert("🇱🇨", "St. Lucia");
        m.insert("🇱🇮", "Liechtenstein");
        m.insert("🇱🇰", "Sri Lanka");
        m.insert("🇱🇷", "Liberia");
        m.insert("🇱🇸", "Lesotho");
        m.insert("🇱🇹", "Lithuania");
        m.insert("🇱🇺", "Luxembourg");
        m.insert("🇱🇻", "Latvia");
        m.insert("🇱🇾", "Libya");
        m.insert("🇲🇦", "Morocco");
        m.insert("🇲🇨", "Monaco");
        m.insert("🇲🇩", "Moldova");
        m.insert("🇲🇪", "Montenegro");
        m.insert("🇲🇫", "St. Martin");
        m.insert("🇲🇬", "Madagascar");
        m.insert("🇲🇭", "Marshall Islands");
        m.insert("🇲🇰", "Macedonia");
        m.insert("🇲🇱", "Mali");
        m.insert("🇲🇲", "Myanmar (Burma)");
        m.insert("🇲🇳", "Mongolia");
        m.insert("🇲🇴", "Macau Sar China");
        m.insert("🇲🇵", "Northern Mariana Islands");
        m.insert("🇲🇶", "Martinique");
        m.insert("🇲🇷", "Mauritania");
        m.insert("🇲🇸", "Montserrat");
        m.insert("🇲🇹", "Malta");
        m.insert("🇲🇺", "Mauritius");
        m.insert("🇲🇻", "Maldives");
        m.insert("🇲🇼", "Malawi");
        m.insert("🇲🇽", "Mexico");
        m.insert("🇲🇾", "Malaysia");
        m.insert("🇲🇿", "Mozambique");
        m.insert("🇳🇦", "Namibia");
        m.insert("🇳🇨", "New Caledonia");
        m.insert("🇳🇪", "Niger");
        m.insert("🇳🇫", "Norfolk Island");
        m.insert("🇳🇬", "Nigeria");
        m.insert("🇳🇮", "Nicaragua");
        m.insert("🇳🇱", "Netherlands");
        m.insert("🇳🇴", "Norway");
        m.insert("🇳🇵", "Nepal");
        m.insert("🇳🇷", "Nauru");
        m.insert("🇳🇺", "Niue");
        m.insert("🇳🇿", "New Zealand");
        m.insert("🇴🇲", "Oman");
        m.insert("🇵🇦", "Panama");
        m.insert("🇵🇪", "Peru");
        m.insert("🇵🇫", "French Polynesia");
        m.insert("🇵🇬", "Papua New Guinea");
        m.insert("🇵🇭", "Philippines");
        m.insert("🇵🇰", "Pakistan");
        m.insert("🇵🇱", "Poland");
        m.insert("🇵🇲", "St. Pierre & Miquelon");
        m.insert("🇵🇳", "Pitcairn Islands");
        m.insert("🇵🇷", "Puerto Rico");
        m.insert("🇵🇸", "Palestinian Territories");
        m.insert("🇵🇹", "Portugal");
        m.insert("🇵🇼", "Palau");
        m.insert("🇵🇾", "Paraguay");
        m.insert("🇶🇦", "Qatar");
        m.insert("🇷🇪", "Réunion");
        m.insert("🇷🇴", "Romania");
        m.insert("🇷🇸", "Serbia");
        m.insert("🇷🇺", "Russia");
        m.insert("🇷🇼", "Rwanda");
        m.insert("🇸🇦", "Saudi Arabia");
        m.insert("🇸🇧", "Solomon Islands");
        m.insert("🇸🇨", "Seychelles");
        m.insert("🇸🇩", "Sudan");
        m.insert("🇸🇪", "Sweden");
        m.insert("🇸🇬", "Singapore");
        m.insert("🇸🇭", "St. Helena");
        m.insert("🇸🇮", "Slovenia");
        m.insert("🇸🇯", "Svalbard & Jan Mayen");
        m.insert("🇸🇰", "Slovakia");
        m.insert("🇸🇱", "Sierra Leone");
        m.insert("🇸🇲", "San Marino");
        m.insert("🇸🇳", "Senegal");
        m.insert("🇸🇴", "Somalia");
        m.insert("🇸🇷", "Suriname");
        m.insert("🇸🇸", "South Sudan");
        m.insert("🇸🇹", "São Tomé & Príncipe");
        m.insert("🇸🇻", "El Salvador");
        m.insert("🇸🇽", "Sint Maarten");
        m.insert("🇸🇾", "Syria");
        m.insert("🇸🇿", "Swaziland");
        m.insert("🇹🇦", "Tristan Da Cunha");
        m.insert("🇹🇨", "Turks & Caicos Islands");
        m.insert("🇹🇩", "Chad");
        m.insert("🇹🇫", "French Southern Territories");
        m.insert("🇹🇬", "Togo");
        m.insert("🇹🇭", "Thailand");
        m.insert("🇹🇯", "Tajikistan");
        m.insert("🇹🇰", "Tokelau");
        m.insert("🇹🇱", "Timor-Leste");
        m.insert("🇹🇲", "Turkmenistan");
        m.insert("🇹🇳", "Tunisia");
        m.insert("🇹🇴", "Tonga");
        m.insert("🇹🇷", "Turkey");
        m.insert("🇹🇹", "Trinidad & Tobago");
        m.insert("🇹🇻", "Tuvalu");
        m.insert("🇹🇼", "Taiwan");
        m.insert("🇹🇿", "Tanzania");
        m.insert("🇺🇦", "Ukraine");
        m.insert("🇺🇬", "Uganda");
        m.insert("🇺🇲", "U.S. Outlying Islands");
        m.insert("🇺🇳", "United Nations");
        m.insert("🇺🇸", "United States");
        m.insert("🇺🇾", "Uruguay");
        m.insert("🇺🇿", "Uzbekistan");
        m.insert("🇻🇦", "Vatican City");
        m.insert("🇻🇨", "St. Vincent & Grenadines");
        m.insert("🇻🇪", "Venezuela");
        m.insert("🇻🇬", "British Virgin Islands");
        m.insert("🇻🇮", "U.S. Virgin Islands");
        m.insert("🇻🇳", "Vietnam");
        m.insert("🇻🇺", "Vanuatu");
        m.insert("🇼🇫", "Wallis & Futuna");
        m.insert("🇼🇸", "Samoa");
        m.insert("🇽🇰", "Kosovo");
        m.insert("🇾🇪", "Yemen");
        m.insert("🇾🇹", "Mayotte");
        m.insert("🇿🇦", "South Africa");
        m.insert("🇿🇲", "Zambia");
        m.insert("🇿🇼", "Zimbabwe");
        m.insert("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "England");
        m.insert("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Scotland");
        m.insert("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "Wales");
        m
    };
}

pub fn flag(name: &str) -> String {
    for (key, val) in FLAGS.iter() {
        if val.to_string() == name {
            return key.to_string();
        }
    }

    return "🚩".to_string();
}
