// glip - Copyright 2019 Tomohisa Oda

use std::collections::HashMap;

pub fn flag(name: &str) -> String {
    let mut map = HashMap::new();

    map.insert("🇦🇨", "Ascension Island");
    map.insert("🇦🇩", "Andorra");
    map.insert("🇦🇪", "United Arab Emirates");
    map.insert("🇦🇫", "Afghanistan");
    map.insert("🇦🇬", "Antigua & Barbuda");
    map.insert("🇦🇮", "Anguilla");
    map.insert("🇦🇱", "Albania");
    map.insert("🇦🇲", "Armenia");
    map.insert("🇦🇴", "Angola");
    map.insert("🇦🇶", "Antarctica");
    map.insert("🇦🇷", "Argentina");
    map.insert("🇦🇸", "American Samoa");
    map.insert("🇦🇹", "Austria");
    map.insert("🇦🇺", "Australia");
    map.insert("🇦🇼", "Aruba");
    map.insert("🇦🇽", "Åland Islands");
    map.insert("🇦🇿", "Azerbaijan");
    map.insert("🇧🇦", "Bosnia & Herzegovina");
    map.insert("🇧🇧", "Barbados");
    map.insert("🇧🇩", "Bangladesh");
    map.insert("🇧🇪", "Belgium");
    map.insert("🇧🇫", "Burkina Faso");
    map.insert("🇧🇬", "Bulgaria");
    map.insert("🇧🇭", "Bahrain");
    map.insert("🇧🇮", "Burundi");
    map.insert("🇧🇯", "Benin");
    map.insert("🇧🇱", "St. Barthélemy");
    map.insert("🇧🇲", "Bermuda");
    map.insert("🇧🇳", "Brunei");
    map.insert("🇧🇴", "Bolivia");
    map.insert("🇧🇶", "Caribbean Netherlands");
    map.insert("🇧🇷", "Brazil");
    map.insert("🇧🇸", "Bahamas");
    map.insert("🇧🇹", "Bhutan");
    map.insert("🇧🇻", "Bouvet Island");
    map.insert("🇧🇼", "Botswana");
    map.insert("🇧🇾", "Belarus");
    map.insert("🇧🇿", "Belize");
    map.insert("🇨🇦", "Canada");
    map.insert("🇨🇨", "Cocos (Keeling) Islands");
    map.insert("🇨🇩", "Congo - Kinshasa");
    map.insert("🇨🇫", "Central African Republic");
    map.insert("🇨🇬", "Congo - Brazzaville");
    map.insert("🇨🇭", "Switzerland");
    map.insert("🇨🇮", "Côte d’Ivoire");
    map.insert("🇨🇰", "Cook Islands");
    map.insert("🇨🇱", "Chile");
    map.insert("🇨🇲", "Cameroon");
    map.insert("🇨🇳", "China");
    map.insert("🇨🇴", "Colombia");
    map.insert("🇨🇵", "Clipperton Island");
    map.insert("🇨🇷", "Costa Rica");
    map.insert("🇨🇺", "Cuba");
    map.insert("🇨🇻", "Cape Verde");
    map.insert("🇨🇼", "Curaçao");
    map.insert("🇨🇽", "Christmas Island");
    map.insert("🇨🇾", "Cyprus");
    map.insert("🇨🇿", "Czechia");
    map.insert("🇩🇪", "Germany");
    map.insert("🇩🇬", "Diego Garcia");
    map.insert("🇩🇯", "Djibouti");
    map.insert("🇩🇰", "Denmark");
    map.insert("🇩🇲", "Dominica");
    map.insert("🇩🇴", "Dominican Republic");
    map.insert("🇩🇿", "Algeria");
    map.insert("🇪🇦", "Ceuta & Melilla");
    map.insert("🇪🇨", "Ecuador");
    map.insert("🇪🇪", "Estonia");
    map.insert("🇪🇬", "Egypt");
    map.insert("🇪🇭", "Western Sahara");
    map.insert("🇪🇷", "Eritrea");
    map.insert("🇪🇸", "Spain");
    map.insert("🇪🇹", "Ethiopia");
    map.insert("🇪🇺", "European Union");
    map.insert("🇫🇮", "Finland");
    map.insert("🇫🇯", "Fiji");
    map.insert("🇫🇰", "Falkland Islands");
    map.insert("🇫🇲", "Micronesia");
    map.insert("🇫🇴", "Faroe Islands");
    map.insert("🇫🇷", "France");
    map.insert("🇬🇦", "Gabon");
    map.insert("🇬🇧", "United Kingdom");
    map.insert("🇬🇩", "Grenada");
    map.insert("🇬🇪", "Georgia");
    map.insert("🇬🇫", "French Guiana");
    map.insert("🇬🇬", "Guernsey");
    map.insert("🇬🇭", "Ghana");
    map.insert("🇬🇮", "Gibraltar");
    map.insert("🇬🇱", "Greenland");
    map.insert("🇬🇲", "Gambia");
    map.insert("🇬🇳", "Guinea");
    map.insert("🇬🇵", "Guadeloupe");
    map.insert("🇬🇶", "Equatorial Guinea");
    map.insert("🇬🇷", "Greece");
    map.insert("🇬🇸", "South Georgia & South Sandwich Islands");
    map.insert("🇬🇹", "Guatemala");
    map.insert("🇬🇺", "Guam");
    map.insert("🇬🇼", "Guinea-Bissau");
    map.insert("🇬🇾", "Guyana");
    map.insert("🇭🇰", "Hong Kong SAR China");
    map.insert("🇭🇲", "Heard & McDonald Islands");
    map.insert("🇭🇳", "Honduras");
    map.insert("🇭🇷", "Croatia");
    map.insert("🇭🇹", "Haiti");
    map.insert("🇭🇺", "Hungary");
    map.insert("🇮🇨", "Canary Islands");
    map.insert("🇮🇩", "Indonesia");
    map.insert("🇮🇪", "Ireland");
    map.insert("🇮🇱", "Israel");
    map.insert("🇮🇲", "Isle of Man");
    map.insert("🇮🇳", "India");
    map.insert("🇮🇴", "British Indian Ocean Territory");
    map.insert("🇮🇶", "Iraq");
    map.insert("🇮🇷", "Iran");
    map.insert("🇮🇸", "Iceland");
    map.insert("🇮🇹", "Italy");
    map.insert("🇯🇪", "Jersey");
    map.insert("🇯🇲", "Jamaica");
    map.insert("🇯🇴", "Jordan");
    map.insert("🇯🇵", "Japan");
    map.insert("🇰🇪", "Kenya");
    map.insert("🇰🇬", "Kyrgyzstan");
    map.insert("🇰🇭", "Cambodia");
    map.insert("🇰🇮", "Kiribati");
    map.insert("🇰🇲", "Comoros");
    map.insert("🇰🇳", "St. Kitts & Nevis");
    map.insert("🇰🇵", "North Korea");
    map.insert("🇰🇷", "South Korea");
    map.insert("🇰🇼", "Kuwait");
    map.insert("🇰🇾", "Cayman Islands");
    map.insert("🇰🇿", "Kazakhstan");
    map.insert("🇱🇦", "Laos");
    map.insert("🇱🇧", "Lebanon");
    map.insert("🇱🇨", "St. Lucia");
    map.insert("🇱🇮", "Liechtenstein");
    map.insert("🇱🇰", "Sri Lanka");
    map.insert("🇱🇷", "Liberia");
    map.insert("🇱🇸", "Lesotho");
    map.insert("🇱🇹", "Lithuania");
    map.insert("🇱🇺", "Luxembourg");
    map.insert("🇱🇻", "Latvia");
    map.insert("🇱🇾", "Libya");
    map.insert("🇲🇦", "Morocco");
    map.insert("🇲🇨", "Monaco");
    map.insert("🇲🇩", "Moldova");
    map.insert("🇲🇪", "Montenegro");
    map.insert("🇲🇫", "St. Martin");
    map.insert("🇲🇬", "Madagascar");
    map.insert("🇲🇭", "Marshall Islands");
    map.insert("🇲🇰", "Macedonia");
    map.insert("🇲🇱", "Mali");
    map.insert("🇲🇲", "Myanmar (Burma)");
    map.insert("🇲🇳", "Mongolia");
    map.insert("🇲🇴", "Macau Sar China");
    map.insert("🇲🇵", "Northern Mariana Islands");
    map.insert("🇲🇶", "Martinique");
    map.insert("🇲🇷", "Mauritania");
    map.insert("🇲🇸", "Montserrat");
    map.insert("🇲🇹", "Malta");
    map.insert("🇲🇺", "Mauritius");
    map.insert("🇲🇻", "Maldives");
    map.insert("🇲🇼", "Malawi");
    map.insert("🇲🇽", "Mexico");
    map.insert("🇲🇾", "Malaysia");
    map.insert("🇲🇿", "Mozambique");
    map.insert("🇳🇦", "Namibia");
    map.insert("🇳🇨", "New Caledonia");
    map.insert("🇳🇪", "Niger");
    map.insert("🇳🇫", "Norfolk Island");
    map.insert("🇳🇬", "Nigeria");
    map.insert("🇳🇮", "Nicaragua");
    map.insert("🇳🇱", "Netherlands");
    map.insert("🇳🇴", "Norway");
    map.insert("🇳🇵", "Nepal");
    map.insert("🇳🇷", "Nauru");
    map.insert("🇳🇺", "Niue");
    map.insert("🇳🇿", "New Zealand");
    map.insert("🇴🇲", "Oman");
    map.insert("🇵🇦", "Panama");
    map.insert("🇵🇪", "Peru");
    map.insert("🇵🇫", "French Polynesia");
    map.insert("🇵🇬", "Papua New Guinea");
    map.insert("🇵🇭", "Philippines");
    map.insert("🇵🇰", "Pakistan");
    map.insert("🇵🇱", "Poland");
    map.insert("🇵🇲", "St. Pierre & Miquelon");
    map.insert("🇵🇳", "Pitcairn Islands");
    map.insert("🇵🇷", "Puerto Rico");
    map.insert("🇵🇸", "Palestinian Territories");
    map.insert("🇵🇹", "Portugal");
    map.insert("🇵🇼", "Palau");
    map.insert("🇵🇾", "Paraguay");
    map.insert("🇶🇦", "Qatar");
    map.insert("🇷🇪", "Réunion");
    map.insert("🇷🇴", "Romania");
    map.insert("🇷🇸", "Serbia");
    map.insert("🇷🇺", "Russia");
    map.insert("🇷🇼", "Rwanda");
    map.insert("🇸🇦", "Saudi Arabia");
    map.insert("🇸🇧", "Solomon Islands");
    map.insert("🇸🇨", "Seychelles");
    map.insert("🇸🇩", "Sudan");
    map.insert("🇸🇪", "Sweden");
    map.insert("🇸🇬", "Singapore");
    map.insert("🇸🇭", "St. Helena");
    map.insert("🇸🇮", "Slovenia");
    map.insert("🇸🇯", "Svalbard & Jan Mayen");
    map.insert("🇸🇰", "Slovakia");
    map.insert("🇸🇱", "Sierra Leone");
    map.insert("🇸🇲", "San Marino");
    map.insert("🇸🇳", "Senegal");
    map.insert("🇸🇴", "Somalia");
    map.insert("🇸🇷", "Suriname");
    map.insert("🇸🇸", "South Sudan");
    map.insert("🇸🇹", "São Tomé & Príncipe");
    map.insert("🇸🇻", "El Salvador");
    map.insert("🇸🇽", "Sint Maarten");
    map.insert("🇸🇾", "Syria");
    map.insert("🇸🇿", "Swaziland");
    map.insert("🇹🇦", "Tristan Da Cunha");
    map.insert("🇹🇨", "Turks & Caicos Islands");
    map.insert("🇹🇩", "Chad");
    map.insert("🇹🇫", "French Southern Territories");
    map.insert("🇹🇬", "Togo");
    map.insert("🇹🇭", "Thailand");
    map.insert("🇹🇯", "Tajikistan");
    map.insert("🇹🇰", "Tokelau");
    map.insert("🇹🇱", "Timor-Leste");
    map.insert("🇹🇲", "Turkmenistan");
    map.insert("🇹🇳", "Tunisia");
    map.insert("🇹🇴", "Tonga");
    map.insert("🇹🇷", "Turkey");
    map.insert("🇹🇹", "Trinidad & Tobago");
    map.insert("🇹🇻", "Tuvalu");
    map.insert("🇹🇼", "Taiwan");
    map.insert("🇹🇿", "Tanzania");
    map.insert("🇺🇦", "Ukraine");
    map.insert("🇺🇬", "Uganda");
    map.insert("🇺🇲", "U.S. Outlying Islands");
    map.insert("🇺🇳", "United Nations");
    map.insert("🇺🇸", "United States");
    map.insert("🇺🇾", "Uruguay");
    map.insert("🇺🇿", "Uzbekistan");
    map.insert("🇻🇦", "Vatican City");
    map.insert("🇻🇨", "St. Vincent & Grenadines");
    map.insert("🇻🇪", "Venezuela");
    map.insert("🇻🇬", "British Virgin Islands");
    map.insert("🇻🇮", "U.S. Virgin Islands");
    map.insert("🇻🇳", "Vietnam");
    map.insert("🇻🇺", "Vanuatu");
    map.insert("🇼🇫", "Wallis & Futuna");
    map.insert("🇼🇸", "Samoa");
    map.insert("🇽🇰", "Kosovo");
    map.insert("🇾🇪", "Yemen");
    map.insert("🇾🇹", "Mayotte");
    map.insert("🇿🇦", "South Africa");
    map.insert("🇿🇲", "Zambia");
    map.insert("🇿🇼", "Zimbabwe");
    map.insert("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "England");
    map.insert("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Scotland");
    map.insert("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "Wales");

    for (key, val) in map.iter() {
        if val.to_string() == name {
            return key.to_string();
        }
    }

    return "🚩".to_string();
}
